# # At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
# C-s = ":w" # Maps the Control-s to the typable command :w which is an alias for :write (save file)
# C-o = ":open ~/.config/helix/config.toml" # Maps the Control-o to opening of the helix config file
# # a = "move_char_left" # Maps the 'a' key to the move_char_left command
# # w = "move_line_up" # Maps the 'w' key move_line_up
# # "C-S-esc" = "extend_line" # Maps Control-Shift-Escape to extend_line
# g = { a = "code_action" } # Maps `ga` to show possible code actions
# "ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode
Z = { Z = ":wq" } # Save and quit
# 
[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
