theme = "catppuccin_mocha"

[editor]
line-number = "relative"

# # At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
C-s = ":w" # Maps the Control-s to the typable command :w which is an alias for :write (save file)
"backspace" = { c = ":config-open", r = ":config-reload", g = ":sh go run main.go", l = ":open ~/dotfiles/helix/languages.toml", p = ":sh python3 main.py" }
# # a = "move_char_left" # Maps the 'a' key to the move_char_left command
# # w = "move_line_up" # Maps the 'w' key move_line_up
# # "C-S-esc" = "extend_line" # Maps Control-Shift-Escape to extend_line
# g = { a = "code_action" } # Maps `ga` to show possible code actions
# "ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode
Z = { Z = ":wq", Q = ":q!" } # Save and quit
# 
[keys.insert]
C-s = ":w"
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

