theme = "catppuccin_mocha"

[editor]
line-number = "relative"
auto-format = true
auto-save = true
rulers = [ 100 ]
color-modes = true
true-color = true
bufferline = "multiple"
scrolloff = 8 
scroll-lines = 5
# shell = [ "zsh" "-c" ]

[editor.lsp]
display-messages = true

# # At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
G = "goto_file_end"
X = "extend_line_above"
ret = ["move_line_down", "goto_line_start"]
C-s = [ "save_selection", ":w" ]
C-S = ":write-all"
Z = { Z = ":wq", Q = ":q!" } # Save and quit
"+" = "repeat_last_motion"

# move line around
C-j = [ "delete_selection", "move_line_down", "paste_before" ]
C-k = [ "delete_selection", "move_line_up", "paste_before" ]

# move around splits
C-h = "jump_view_left"
C-l = "jump_view_right"

[keys.normal.backspace]
c = ":config-open"
R = ":config-reload"
r = ":sh cargo run"
g = ":sh go run main.go"
l = ":open ~/dotfiles/helix/languages.toml"
p = ":sh python3 main.py"
a = ":open ~/dotfiles/shell/aliases"
e = ":open ~/dotfiles/shell/exports"


[keys.normal.space]
q = ":q"
w = ":w"
"space" = ["last_picker"]


[keys.insert]
C-s = ":w"

