# Note: this key must come **before** the [[language]] and [[grammar]] sections
use-grammars = { only = [ "go", "python", "rust" ], except = [] }


[[language]]
name = "python"
file-types = ["py"]
auto-format = true


[[language]]
name = "golang"
# scope = "main.go"
roots = [ "go.mod", "go.sum" ]
file-types = ["go", "gomod"]
auto-format = true



